PersonelMVCUI/Models/EntityFramework/Departman.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonelMVCUI.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departman()
        {
            this.Personel = new HashSet<Personel>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Personel> Personel { get; set; }
    }
}

PersonelMVCUI/Controllers/DepartmanController.cs
using PersonelMVCUI.Models.EntityFramework;
using PersonelMVCUI.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PersonelMVCUI.Controllers
{
    [Authorize(Roles = "A, U")]
    
    public class DepartmanController : Controller
    {
        PersonelDbEntities db = new PersonelDbEntities(); 

        // GET: Departman

        
        public ActionResult Index()
        {
            var model = db.Departman.ToList();
            // int a = 10, b = 0;
            // int c = a / b;
            return View(model);
        }

        [HttpGet]
        public ActionResult Yeni()
        {            
            return View("DepartmanForm", new Departman());
        }

      [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Departman departman)
        {
            if (!ModelState.IsValid)
            {
                return View("DepartmanForm");
            }

            MesajViewModel model = new MesajViewModel();

            if (departman.Id == 0)
            {
                db.Departman.Add(departman);
                model.Mesaj = departman.Ad + " başarıyla eklendi.";
            }
            else
            {
                var guncellenecekDepartman = db.Departman.Find(departman.Id);
                if (guncellenecekDepartman == null)
                {
                    return HttpNotFound();
                }
                else
                {
                    guncellenecekDepartman.Ad = departman.Ad;
                    // guncellenecekDepartman.Id = departman.Id;
                    model.Mesaj = departman.Ad + " başarıyla güncellendi.";
                }
            }
            db.SaveChanges();

            model.Status = true;
            model.LinkText = "Departman Listesi";
            model.Url = "/Departman";

            return View("_Mesaj", model);
        }

        public ActionResult Guncelle(int id)
        {
            var model = db.Departman.Find(id);
            if (model == null)
            {
                return HttpNotFound();
            }
            return View("DepartmanForm", model);
        }

        public ActionResult Sil(int id)
        {
            var silinecekDepartman = db.Departman.Find(id);
            if (silinecekDepartman == null)
                return HttpNotFound();
            db.Departman.Remove(silinecekDepartman);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

PersonelMVCUI/Controllers/PersonelController.cs
using PersonelMVCUI.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PersonelMVCUI.ViewModels;

namespace PersonelMVCUI.Controllers
{
    [Authorize(Roles = "A, U")]
    public class PersonelController : Controller
    {

        PersonelDbEntities db = new PersonelDbEntities();
        // GET: Personel

        [OutputCache(Duration = 30)]
        public ActionResult Index()
        {
            var model = db.Personel.Include(x=>x.Departman).ToList();
            return View(model);
        }

        
        public ActionResult Yeni()
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel = new Personel()
            };
            return View("PersonelForm", model);
        }

        [ValidateAntiForgeryToken]
        public ActionResult Kaydet(Personel personel)
        {
            if (!ModelState.IsValid)
            {
                var model = new PersonelFormViewModel()
                {
                    Departmanlar = db.Departman.ToList(),
                    Personel = personel
                };
                return View("PersonelForm", model);
            }
            if (personel.Id==0) //Ekleme
            {
                db.Personel.Add(personel);
            }
            else //Guncelleme
            {
                db.Entry(personel).State = System.Data.Entity.EntityState.Modified;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Guncelle(int id)
        {
            var model = new PersonelFormViewModel()
            {
                Departmanlar = db.Departman.ToList(),
                Personel = db.Personel.Find(id)
            };
            return View("PersonelForm", model);
        }
        public ActionResult Sil(int id)
        {
            var silinecekPersonel = db.Personel.Find(id);
            if (silinecekPersonel==null)
            {
                return HttpNotFound();
            }
            db.Personel.Remove(silinecekPersonel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult PersonelleriListele(int id)
        {
            var model = db.Personel.Where(x => x.DepartmanId == id).ToList();
            return PartialView(model);
        }

        public ActionResult ToplamMaas()
        {
            ViewBag.Maas = db.Personel.Sum(x=>x.Maas);
            return PartialView();
        }
    }
}

PersonelMVCUI/Views/Departman/DepartmanForm.cshtml
@model PersonelMVCUI.Models.EntityFramework.Departman
@{
    ViewBag.Title = "Yeni";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="mesaj"></div>
@using (Ajax.BeginForm("Kaydet", "Departman", new AjaxOptions { HttpMethod="POST", UpdateTargetId="mesaj"}))
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(m => m.Ad)
        @Html.TextBoxFor(m => m.Ad, new { @class = "form-control" })
        @Html.ValidationMessageFor(m => m.Ad)
    </div>
    @Html.HiddenFor(m => m.Id)
    <button type="submit" class="btn btn-success">Kaydet</button>
}

@section scripts
    {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    }

PersonelMVCUI/Views/Departman/Index.cshtml
@using PersonelMVCUI.Models.EntityFramework
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<a class="btn btn-success" href="/Departman/Yeni">Yeni Departman</a>
<h2>Departman Listesi</h2>
<table class="table table-bordered" id="tblDepartmanlar">
    <thead>
        <tr>
            <th>ID</th>
            <th>Ad</th>
            <th>Güncelle</th>
            <th>Sil</th>
            <th>Personeller</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var departman in Model)
        {
        <tr>
            <td>@departman.Id</td>
            <td>@departman.Ad</td>
            <td><a class="btn btn-primary" href="/Departman/Guncelle/@departman.Id">Güncelle</a></td>
            <td><a class="btn btn-warning btnDepartmanSil" data-id="@departman.Id">Sil</a></td>
            <td>@Ajax.ActionLink("Personelleri Göster", "PersonelleriListele", "Personel", new { id = departman.Id }, new AjaxOptions { HttpMethod="GET", UpdateTargetId="personelListesi"}, new { @class="btn btn-primary"})</td>
        </tr>
        }
    </tbody>
</table>

<div id="personelListesi"></div>